"""Web UI chat application services."""

from apeiria.chat.alconna import register_webchat_uninfo, register_webchat_uniseg
from apeiria.chat.connection import WebChatConnection
from apeiria.chat.gateway import (
    ChatAssetFileMissingError,
    ChatAssetNotFoundError,
    ChatAuthError,
    ChatGatewayService,
    chat_gateway_service,
)
from apeiria.chat.gateway_protocol import (
    AuthHelloPayload,
    AuthOkPayload,
    CapabilitiesResponsePayload,
    ChatCapabilities,
    ChatEnvelope,
    ChatSegment,
    ChatSessionState,
    EnvelopeVersion,
    ErrorPayload,
    ImageSegment,
    MentionSegment,
    MessageAckPayload,
    MessageReceivePayload,
    MessageSendPayload,
    RawSegment,
    ReplySegment,
    SessionCreatePayload,
    SessionDeletedPayload,
    SessionDeletePayload,
    SessionListItem,
    SessionListPayload,
    SessionStatePayload,
    SessionStatus,
    SessionUpdatePayload,
    SystemMessagePayload,
    TextSegment,
    WebUIPrincipal,
)
from apeiria.chat.service import WebChatService, web_chat_service

register_webchat_uniseg()
register_webchat_uninfo()

__all__ = [
    "AuthHelloPayload",
    "AuthOkPayload",
    "CapabilitiesResponsePayload",
    "ChatAssetFileMissingError",
    "ChatAssetNotFoundError",
    "ChatAuthError",
    "ChatCapabilities",
    "ChatEnvelope",
    "ChatGatewayService",
    "ChatSegment",
    "ChatSessionState",
    "EnvelopeVersion",
    "ErrorPayload",
    "ImageSegment",
    "MentionSegment",
    "MessageAckPayload",
    "MessageReceivePayload",
    "MessageSendPayload",
    "RawSegment",
    "ReplySegment",
    "SessionCreatePayload",
    "SessionDeletePayload",
    "SessionDeletedPayload",
    "SessionListItem",
    "SessionListPayload",
    "SessionStatePayload",
    "SessionStatus",
    "SessionUpdatePayload",
    "SystemMessagePayload",
    "TextSegment",
    "WebChatConnection",
    "WebChatService",
    "WebUIPrincipal",
    "chat_gateway_service",
    "web_chat_service",
]
