"""initial schema

Revision ID: 0907ade3a5d7
Revises: 
Create Date: 2026-06-12 21:45:32.081226
"""

from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = '0907ade3a5d7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_rule',
    sa.Column('subject_type', sa.Text(), nullable=False),
    sa.Column('subject_id', sa.Text(), nullable=False),
    sa.Column('plugin_id', sa.Text(), nullable=False),
    sa.Column('effect', sa.Text(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.Integer(), nullable=False),
    sa.CheckConstraint("effect IN ('allow', 'deny')", name='ck_access_rule_effect'),
    sa.CheckConstraint("subject_type IN ('user', 'group')", name='ck_access_rule_subject_type'),
    sa.PrimaryKeyConstraint('subject_type', 'subject_id', 'plugin_id')
    )
    op.create_table('ai_affinity',
    sa.Column('affinity_id', sa.Text(), nullable=False),
    sa.Column('platform', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('mood_tags_json', sa.Text(), nullable=False),
    sa.Column('last_event_at', sa.Integer(), nullable=False),
    sa.Column('last_decay_at', sa.Integer(), nullable=True),
    sa.CheckConstraint('score BETWEEN -100 AND 100', name='ck_ai_affinity_score'),
    sa.PrimaryKeyConstraint('affinity_id'),
    sa.UniqueConstraint('platform', 'user_id', name='uq_ai_affinity_platform_user')
    )
    op.create_index('ix_ai_affinity_user', 'ai_affinity', ['platform', 'user_id'], unique=False)
    op.create_table('ai_knowledge_document',
    sa.Column('document_id', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('source_file_name', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.Text(), nullable=False),
    sa.Column('content_text', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.Integer(), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'embedded', 'degraded', 'failed')", name='ck_ai_knowledge_document_status'),
    sa.CheckConstraint('chunk_count >= 0', name='ck_ai_knowledge_document_chunk_count'),
    sa.PrimaryKeyConstraint('document_id')
    )
    op.create_index('ix_ai_knowledge_document_updated_at', 'ai_knowledge_document', ['updated_at'], unique=False)
    op.create_table('ai_model_route',
    sa.Column('route_id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('task_class', sa.Text(), nullable=False),
    sa.Column('mode', sa.Text(), nullable=False),
    sa.Column('algorithm', sa.Text(), nullable=False),
    sa.Column('fallback_on_failure', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.Integer(), nullable=False),
    sa.CheckConstraint("algorithm IN ('ordered', 'weighted_random')", name='ck_ai_model_route_algorithm'),
    sa.CheckConstraint("mode != 'load_balance' OR algorithm = 'weighted_random'", name='ck_ai_model_route_mode_weighted'),
    sa.CheckConstraint("mode != 'primary_fallback' OR algorithm = 'ordered'", name='ck_ai_model_route_mode_ordered'),
    sa.CheckConstraint("mode IN ('primary_fallback', 'load_balance')", name='ck_ai_model_route_mode'),
    sa.CheckConstraint("task_class IN ('planner_light', 'reply_default', 'reply_roleplay', 'reasoning_heavy', 'memory_extraction', 'tool_orchestration')", name='ck_ai_model_route_task_class'),
    sa.CheckConstraint('enabled IN (0, 1)', name='ck_ai_model_route_enabled'),
    sa.CheckConstraint('fallback_on_failure IN (0, 1)', name='ck_ai_model_route_fallback_on_failure'),
    sa.CheckConstraint('length(name) > 0', name='ck_ai_model_route_name_len'),
    sa.PrimaryKeyConstraint('route_id')
    )
    op.create_index('idx_ai_model_route_task_class', 'ai_model_route', ['task_class', 'enabled'], unique=False)
    op.create_table('ai_model_usage_event',
    sa.Column('usage_event_id', sa.Text(), nullable=False),
    sa.Column('trace_id', sa.Text(), nullable=False),
    sa.Column('session_id', sa.Text(), nullable=False),
    sa.Column('runtime_mode', sa.Text(), nullable=False),
    sa.Column('response_source', sa.Text(), nullable=False),
    sa.Column('source_id', sa.Text(), nullable=False),
    sa.Column('model_name', sa.Text(), nullable=False),
    sa.Column('operation', sa.Text(), nullable=False),
    sa.Column('attempt_index', sa.Integer(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('usage_available', sa.Integer(), nullable=False),
    sa.Column('measurement_source', sa.Text(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('cached_input_tokens', sa.Integer(), nullable=True),
    sa.Column('reasoning_tokens', sa.Integer(), nullable=True),
    sa.Column('audio_input_tokens', sa.Integer(), nullable=True),
    sa.Column('audio_output_tokens', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.CheckConstraint("measurement_source IN ('provider', 'missing')", name='ck_ai_model_usage_event_measurement_source'),
    sa.CheckConstraint('attempt_index >= 1', name='ck_ai_model_usage_event_attempt_index'),
    sa.CheckConstraint('audio_input_tokens IS NULL OR audio_input_tokens >= 0', name='ck_ai_model_usage_event_audio_input_tokens'),
    sa.CheckConstraint('audio_output_tokens IS NULL OR audio_output_tokens >= 0', name='ck_ai_model_usage_event_audio_output_tokens'),
    sa.CheckConstraint('cached_input_tokens IS NULL OR cached_input_tokens >= 0', name='ck_ai_model_usage_event_cached_input_tokens'),
    sa.CheckConstraint('input_tokens IS NULL OR input_tokens >= 0', name='ck_ai_model_usage_event_input_tokens'),
    sa.CheckConstraint('output_tokens IS NULL OR output_tokens >= 0', name='ck_ai_model_usage_event_output_tokens'),
    sa.CheckConstraint('reasoning_tokens IS NULL OR reasoning_tokens >= 0', name='ck_ai_model_usage_event_reasoning_tokens'),
    sa.CheckConstraint('total_tokens IS NULL OR total_tokens >= 0', name='ck_ai_model_usage_event_total_tokens'),
    sa.CheckConstraint('usage_available IN (0, 1)', name='ck_ai_model_usage_event_usage_available'),
    sa.PrimaryKeyConstraint('usage_event_id')
    )
    op.create_index('ix_ai_model_usage_event_created_at', 'ai_model_usage_event', ['created_at'], unique=False)
    op.create_index('ix_ai_model_usage_event_session', 'ai_model_usage_event', ['session_id', 'created_at'], unique=False)
    op.create_index('ix_ai_model_usage_event_trace', 'ai_model_usage_event', ['trace_id', 'created_at'], unique=False)
    op.create_table('ai_model_usage_hourly',
    sa.Column('hour_bucket', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Text(), nullable=False),
    sa.Column('model_name', sa.Text(), nullable=False),
    sa.Column('operation', sa.Text(), nullable=False),
    sa.Column('call_count', sa.Integer(), nullable=False),
    sa.Column('measured_call_count', sa.Integer(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('cached_input_tokens', sa.Integer(), nullable=False),
    sa.Column('reasoning_tokens', sa.Integer(), nullable=False),
    sa.Column('audio_input_tokens', sa.Integer(), nullable=False),
    sa.Column('audio_output_tokens', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('hour_bucket', 'source_id', 'model_name', 'operation')
    )
    op.create_table('ai_persona',
    sa.Column('persona_id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('style_prompt', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.Integer(), nullable=False),
    sa.CheckConstraint('enabled IN (0, 1)', name='ck_ai_persona_enabled'),
    sa.PrimaryKeyConstraint('persona_id')
    )
    op.create_table('ai_profile',
    sa.Column('profile_id', sa.Text(), nullable=False),
    sa.Column('platform', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=True),
    sa.Column('preferred_name', sa.Text(), nullable=True),
    sa.Column('name_source', sa.Text(), nullable=True),
    sa.Column('name_visibility', sa.Text(), nullable=False),
    sa.Column('profile_enabled', sa.Integer(), nullable=False),
    sa.Column('last_interaction_at', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.Integer(), nullable=False),
    sa.CheckConstraint("name_source IS NULL OR name_source IN ('manual', 'self_introduced', 'platform', 'inferred')", name='ck_ai_profile_name_source'),
    sa.CheckConstraint("name_visibility IN ('private_only', 'public_allowed', 'disabled')", name='ck_ai_profile_name_visibility'),
    sa.CheckConstraint('profile_enabled IN (0, 1)', name='ck_ai_profile_profile_enabled'),
    sa.PrimaryKeyConstraint('profile_id'),
    sa.UniqueConstraint('platform', 'user_id', name='uq_ai_profile_platform_user')
    )
    op.create_index('ix_ai_profile_last_interaction', 'ai_profile', ['last_interaction_at'], unique=False)
    op.create_table('ai_runtime_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('allow_group_initiative', sa.Integer(), nullable=True),
    sa.Column('quiet_hours_enabled', sa.Integer(), nullable=True),
    sa.Column('quiet_hours_start_minute', sa.Integer(), nullable=True),
    sa.Column('quiet_hours_end_minute', sa.Integer(), nullable=True),
    sa.Column('night_awake_lease_minutes', sa.Integer(), nullable=True),
    sa.Column('stt_input_enabled', sa.Integer(), nullable=True),
    sa.Column('persist_raw_event_payloads', sa.Integer(), nullable=True),
    sa.Column('ambient_merge_window_ms', sa.Integer(), nullable=True),
    sa.Column('max_pending_messages', sa.Integer(), nullable=True),
    sa.Column('group_reply_cooldown_seconds', sa.Integer(), nullable=True),
    sa.Column('max_consecutive_ambient_replies', sa.Integer(), nullable=True),
    sa.Column('direct_bypass_ambient_budget', sa.Integer(), nullable=True),
    sa.Column('duplicate_event_ttl_seconds', sa.Integer(), nullable=True),
    sa.Column('tool_execution_timeout_seconds', sa.Float(), nullable=True),
    sa.Column('cleanup_interval_minutes', sa.Integer(), nullable=True),
    sa.Column('conversation_retention_days', sa.Integer(), nullable=True),
    sa.Column('raw_event_retention_days', sa.Integer(), nullable=True),
    sa.Column('tool_execution_retention_days', sa.Integer(), nullable=True),
    sa.Column('suppressed_memory_retention_days', sa.Integer(), nullable=True),
    sa.Column('relationship_event_retention_days', sa.Integer(), nullable=True),
    sa.Column('future_task_retention_days', sa.Integer(), nullable=True),
    sa.Column('trace_enabled', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.Integer(), nullable=False),
    sa.CheckConstraint('allow_group_initiative IS NULL OR allow_group_initiative IN (0, 1)', name='ck_ai_runtime_settings_allow_group_initiative'),
    sa.CheckConstraint('ambient_merge_window_ms IS NULL OR ambient_merge_window_ms >= 0', name='ck_ai_runtime_settings_ambient_merge_window_ms'),
    sa.CheckConstraint('cleanup_interval_minutes IS NULL OR cleanup_interval_minutes >= 1', name='ck_ai_runtime_settings_cleanup_interval_minutes'),
    sa.CheckConstraint('conversation_retention_days IS NULL OR conversation_retention_days >= 1', name='ck_ai_runtime_settings_conversation_retention_days'),
    sa.CheckConstraint('direct_bypass_ambient_budget IS NULL OR direct_bypass_ambient_budget IN (0, 1)', name='ck_ai_runtime_settings_direct_bypass_ambient_budget'),
    sa.CheckConstraint('duplicate_event_ttl_seconds IS NULL OR duplicate_event_ttl_seconds >= 1', name='ck_ai_runtime_settings_duplicate_event_ttl_seconds'),
    sa.CheckConstraint('future_task_retention_days IS NULL OR future_task_retention_days >= 1', name='ck_ai_runtime_settings_future_task_retention_days'),
    sa.CheckConstraint('group_reply_cooldown_seconds IS NULL OR group_reply_cooldown_seconds >= 0', name='ck_ai_runtime_settings_group_reply_cooldown_seconds'),
    sa.CheckConstraint('id = 1', name='ck_ai_runtime_settings_singleton'),
    sa.CheckConstraint('max_consecutive_ambient_replies IS NULL OR max_consecutive_ambient_replies >= 0', name='ck_ai_runtime_settings_max_consecutive_ambient_replies'),
    sa.CheckConstraint('max_pending_messages IS NULL OR max_pending_messages >= 1', name='ck_ai_runtime_settings_max_pending_messages'),
    sa.CheckConstraint('night_awake_lease_minutes IS NULL OR (night_awake_lease_minutes >= 1 AND night_awake_lease_minutes <= 120)', name='ck_ai_runtime_settings_night_awake_lease_minutes'),
    sa.CheckConstraint('persist_raw_event_payloads IS NULL OR persist_raw_event_payloads IN (0, 1)', name='ck_ai_runtime_settings_persist_raw_event_payloads'),
    sa.CheckConstraint('quiet_hours_enabled IS NULL OR quiet_hours_enabled IN (0, 1)', name='ck_ai_runtime_settings_quiet_hours_enabled'),
    sa.CheckConstraint('quiet_hours_end_minute IS NULL OR (quiet_hours_end_minute >= 0 AND quiet_hours_end_minute <= 1439)', name='ck_ai_runtime_settings_quiet_hours_end_minute'),
    sa.CheckConstraint('quiet_hours_start_minute IS NULL OR (quiet_hours_start_minute >= 0 AND quiet_hours_start_minute <= 1439)', name='ck_ai_runtime_settings_quiet_hours_start_minute'),
    sa.CheckConstraint('raw_event_retention_days IS NULL OR raw_event_retention_days >= 1', name='ck_ai_runtime_settings_raw_event_retention_days'),
    sa.CheckConstraint('relationship_event_retention_days IS NULL OR relationship_event_retention_days >= 1', name='ck_ai_runtime_settings_relationship_event_retention_days'),
    sa.CheckConstraint('stt_input_enabled IS NULL OR stt_input_enabled IN (0, 1)', name='ck_ai_runtime_settings_stt_input_enabled'),
    sa.CheckConstraint('suppressed_memory_retention_days IS NULL OR suppressed_memory_retention_days >= 1', name='ck_ai_runtime_settings_suppressed_memory_retention_days'),
    sa.CheckConstraint('tool_execution_retention_days IS NULL OR tool_execution_retention_days >= 1', name='ck_ai_runtime_settings_tool_execution_retention_days'),
    sa.CheckConstraint('tool_execution_timeout_seconds IS NULL OR tool_execution_timeout_seconds > 0', name='ck_ai_runtime_settings_tool_execution_timeout_seconds'),
    sa.CheckConstraint('trace_enabled IS NULL OR trace_enabled IN (0, 1)', name='ck_ai_runtime_settings_trace_enabled'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_source',
    sa.Column('source_id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('capability_type', sa.Text(), nullable=False),
    sa.Column('client_type', sa.Text(), nullable=False),
    sa.Column('adapter_kind', sa.Text(), nullable=False),
    sa.Column('preset_type', sa.Text(), nullable=False),
    sa.Column('api_base', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Integer(), nullable=False),
    sa.Column('timeout_seconds', sa.Integer(), nullable=True),
    sa.Column('custom_headers_json', sa.Text(), nullable=False),
    sa.Column('extra_config_json', sa.Text(), nullable=False),
    sa.Column('capability_metadata_json', sa.Text(), nullable=False),
    sa.Column('default_options_json', sa.Text(), nullable=False),
    sa.Column('capability_provenance_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.Integer(), nullable=False),
    sa.CheckConstraint("adapter_kind IN ('openai_compatible', 'anthropic_compatible', 'generic_rerank', 'gemini_native', 'ollama_native')", name='ck_ai_source_adapter_kind'),
    sa.CheckConstraint("capability_type IN ('chat_completion', 'embedding', 'speech_to_text', 'text_to_speech', 'rerank')", name='ck_ai_source_capability_type'),
    sa.CheckConstraint("client_type IN ('openai', 'anthropic', 'generic_rerank', 'gemini', 'ollama')", name='ck_ai_source_client_type'),
    sa.CheckConstraint("preset_type IN ('openai_compatible', 'openai_compatible_embedding', 'openai_compatible_stt', 'openai_compatible_tts', 'generic_rerank_api', 'anthropic_compatible', 'gemini_native', 'gemini_native_embedding', 'ollama_native', 'ollama_native_embedding')", name='ck_ai_source_preset_type'),
    sa.CheckConstraint('enabled IN (0, 1)', name='ck_ai_source_enabled'),
    sa.CheckConstraint('json_valid(capability_metadata_json)', name='ck_ai_source_capability_metadata_json'),
    sa.CheckConstraint('json_valid(capability_provenance_json)', name='ck_ai_source_capability_provenance_json'),
    sa.CheckConstraint('json_valid(custom_headers_json)', name='ck_ai_source_custom_headers_json'),
    sa.CheckConstraint('json_valid(default_options_json)', name='ck_ai_source_default_options_json'),
    sa.CheckConstraint('json_valid(extra_config_json)', name='ck_ai_source_extra_config_json'),
    sa.CheckConstraint('timeout_seconds IS NULL OR timeout_seconds > 0', name='ck_ai_source_timeout_seconds'),
    sa.PrimaryKeyConstraint('source_id')
    )
    op.create_table('ai_tool_policy',
    sa.Column('binding_id', sa.Text(), nullable=False),
    sa.Column('scope_type', sa.Text(), nullable=False),
    sa.Column('scope_id', sa.Text(), nullable=False),
    sa.Column('allowed_level', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.Integer(), nullable=False),
    sa.CheckConstraint("allowed_level IN ('none', 'read', 'write', 'host', 'admin')", name='ck_ai_tool_policy_allowed_level'),
    sa.CheckConstraint("scope_type != 'global' OR scope_id = '__global__'", name='ck_ai_tool_policy_global_scope'),
    sa.CheckConstraint("scope_type IN ('global', 'group', 'user', 'conversation')", name='ck_ai_tool_policy_scope_type'),
    sa.CheckConstraint('length(scope_id) > 0', name='ck_ai_tool_policy_scope_id_len'),
    sa.PrimaryKeyConstraint('binding_id'),
    sa.UniqueConstraint('scope_type', 'scope_id', name='uq_ai_tool_policy_scope')
    )
    op.create_table('apeiria_schema_meta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schema_line', sa.Text(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.Integer(), nullable=False),
    sa.CheckConstraint('id = 1', name='ck_apeiria_schema_meta_singleton'),
    sa.CheckConstraint('length(schema_line) > 0', name='ck_schema_line_nonempty'),
    sa.CheckConstraint('schema_version > 0', name='ck_schema_version_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_session',
    sa.Column('session_id', sa.Text(), nullable=False),
    sa.Column('platform', sa.Text(), nullable=False),
    sa.Column('bot_id', sa.Text(), nullable=False),
    sa.Column('scene_type', sa.Text(), nullable=False),
    sa.Column('scene_id', sa.Text(), nullable=False),
    sa.Column('subject_id', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('extra_json', sa.Text(), nullable=True),
    sa.Column('last_message_at', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.Integer(), nullable=False),
    sa.CheckConstraint("scene_type IN ('group', 'private')", name='ck_chat_session_scene_type'),
    sa.PrimaryKeyConstraint('session_id'),
    sa.UniqueConstraint('platform', 'bot_id', 'scene_type', 'scene_id', name='uq_chat_session_identity')
    )
    op.create_index('idx_chat_session_last_message_at', 'chat_session', ['last_message_at'], unique=False)
    op.create_table('group_state',
    sa.Column('group_id', sa.Text(), nullable=False),
    sa.Column('group_name', sa.Text(), nullable=True),
    sa.Column('bot_enabled', sa.Integer(), nullable=False),
    sa.Column('disabled_plugins_json', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.Integer(), nullable=False),
    sa.CheckConstraint('bot_enabled IN (0, 1)', name='ck_group_state_bot_enabled'),
    sa.PrimaryKeyConstraint('group_id')
    )
    op.create_table('plugin_state',
    sa.Column('plugin_id', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Integer(), nullable=False),
    sa.Column('access_mode', sa.Text(), nullable=False),
    sa.Column('protection_mode', sa.Text(), nullable=False),
    sa.Column('ui_hidden_override', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.Integer(), nullable=False),
    sa.CheckConstraint("access_mode IN ('default_allow', 'default_deny')", name='ck_plugin_state_access_mode'),
    sa.CheckConstraint("protection_mode IN ('normal', 'required')", name='ck_plugin_state_protection_mode'),
    sa.CheckConstraint('enabled IN (0, 1)', name='ck_plugin_state_enabled'),
    sa.CheckConstraint('ui_hidden_override IS NULL OR ui_hidden_override IN (0, 1)', name='ck_plugin_state_ui_hidden_override'),
    sa.PrimaryKeyConstraint('plugin_id')
    )
    op.create_table('webui_account',
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('is_disabled', sa.Integer(), nullable=False),
    sa.Column('last_login_at', sa.Integer(), nullable=True),
    sa.Column('password_changed_at', sa.Integer(), nullable=True),
    sa.Column('session_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.Integer(), nullable=False),
    sa.CheckConstraint('is_disabled IN (0, 1)', name='ck_webui_account_is_disabled'),
    sa.CheckConstraint('length(password_hash) > 0', name='ck_webui_account_password_hash'),
    sa.CheckConstraint('length(username) > 0', name='ck_webui_account_username'),
    sa.CheckConstraint('session_version >= 0', name='ck_webui_account_session_version'),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('username')
    )
    op.create_index('idx_webui_account_username', 'webui_account', ['username'], unique=False)
    op.create_table('webui_auth_secret',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_secret', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.Integer(), nullable=False),
    sa.CheckConstraint('id = 1', name='ck_webui_auth_secret_singleton'),
    sa.CheckConstraint('length(token_secret) > 0', name='ck_webui_auth_secret_nonempty'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_chat_model',
    sa.Column('model_id', sa.Text(), nullable=False),
    sa.Column('source_id', sa.Text(), nullable=False),
    sa.Column('model_identifier', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Integer(), nullable=False),
    sa.Column('is_default', sa.Integer(), nullable=False),
    sa.Column('extra_params_json', sa.Text(), nullable=False),
    sa.Column('capability_metadata_json', sa.Text(), nullable=False),
    sa.Column('default_options_json', sa.Text(), nullable=False),
    sa.Column('capability_provenance_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.Integer(), nullable=False),
    sa.CheckConstraint('enabled IN (0, 1)', name='ck_ai_chat_model_enabled'),
    sa.CheckConstraint('is_default IN (0, 1)', name='ck_ai_chat_model_is_default'),
    sa.CheckConstraint('json_valid(capability_metadata_json)', name='ck_ai_chat_model_capability_metadata_json'),
    sa.CheckConstraint('json_valid(capability_provenance_json)', name='ck_ai_chat_model_capability_provenance_json'),
    sa.CheckConstraint('json_valid(default_options_json)', name='ck_ai_chat_model_default_options_json'),
    sa.CheckConstraint('json_valid(extra_params_json)', name='ck_ai_chat_model_extra_params_json'),
    sa.ForeignKeyConstraint(['source_id'], ['ai_source.source_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('model_id'),
    sa.UniqueConstraint('source_id', 'model_identifier')
    )
    op.create_index('idx_ai_chat_model_one_default_per_source', 'ai_chat_model', ['source_id'], unique=True, sqlite_where=sa.text('is_default = 1'))
    op.create_index('idx_ai_chat_model_source_id', 'ai_chat_model', ['source_id'], unique=False)
    op.create_table('ai_embedding_model',
    sa.Column('model_id', sa.Text(), nullable=False),
    sa.Column('source_id', sa.Text(), nullable=False),
    sa.Column('model_identifier', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Integer(), nullable=False),
    sa.Column('is_default', sa.Integer(), nullable=False),
    sa.Column('extra_params_json', sa.Text(), nullable=False),
    sa.Column('capability_metadata_json', sa.Text(), nullable=False),
    sa.Column('default_options_json', sa.Text(), nullable=False),
    sa.Column('capability_provenance_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.Integer(), nullable=False),
    sa.CheckConstraint('enabled IN (0, 1)', name='ck_ai_embedding_model_enabled'),
    sa.CheckConstraint('is_default IN (0, 1)', name='ck_ai_embedding_model_is_default'),
    sa.CheckConstraint('json_valid(capability_metadata_json)', name='ck_ai_embedding_model_capability_metadata_json'),
    sa.CheckConstraint('json_valid(capability_provenance_json)', name='ck_ai_embedding_model_capability_provenance_json'),
    sa.CheckConstraint('json_valid(default_options_json)', name='ck_ai_embedding_model_default_options_json'),
    sa.CheckConstraint('json_valid(extra_params_json)', name='ck_ai_embedding_model_extra_params_json'),
    sa.ForeignKeyConstraint(['source_id'], ['ai_source.source_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('model_id'),
    sa.UniqueConstraint('source_id', 'model_identifier')
    )
    op.create_index('idx_ai_embedding_model_one_default_per_source', 'ai_embedding_model', ['source_id'], unique=True, sqlite_where=sa.text('is_default = 1'))
    op.create_index('idx_ai_embedding_model_source_id', 'ai_embedding_model', ['source_id'], unique=False)
    op.create_table('ai_future_task',
    sa.Column('task_id', sa.Text(), nullable=False),
    sa.Column('session_id', sa.Text(), nullable=False),
    sa.Column('platform', sa.Text(), nullable=False),
    sa.Column('scene_type', sa.Text(), nullable=False),
    sa.Column('scene_id', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('trigger_at', sa.Integer(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('source_message_id', sa.Text(), nullable=True),
    sa.Column('scheduler_job_id', sa.Text(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('claim_count', sa.Integer(), nullable=False),
    sa.Column('claimed_at', sa.Integer(), nullable=True),
    sa.Column('completed_at', sa.Integer(), nullable=True),
    sa.Column('recovery_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.Integer(), nullable=False),
    sa.CheckConstraint("scene_type IN ('group', 'private')", name='ck_ai_future_task_scene_type'),
    sa.CheckConstraint("status IN ('pending', 'running', 'sent', 'cancelled', 'failed')", name='ck_ai_future_task_status'),
    sa.CheckConstraint('claim_count >= 0', name='ck_ai_future_task_claim_count'),
    sa.ForeignKeyConstraint(['session_id'], ['chat_session.session_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.create_index('ix_ai_future_task_session', 'ai_future_task', ['session_id'], unique=False)
    op.create_index('ix_ai_future_task_status_trigger', 'ai_future_task', ['status', 'trigger_at'], unique=False)
    op.create_index('ix_ai_future_task_updated_at', 'ai_future_task', ['updated_at'], unique=False)
    op.create_table('ai_knowledge_chunk',
    sa.Column('chunk_id', sa.Text(), nullable=False),
    sa.Column('document_id', sa.Text(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('chunk_hash', sa.Text(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('char_count', sa.Integer(), nullable=False),
    sa.Column('embedding_model', sa.Text(), nullable=True),
    sa.Column('embedding_status', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.Integer(), nullable=False),
    sa.CheckConstraint("embedding_status IN ('missing', 'embedded', 'stale', 'failed')", name='ck_ai_knowledge_chunk_embedding_status'),
    sa.CheckConstraint('char_count >= 0', name='ck_ai_knowledge_chunk_char_count'),
    sa.CheckConstraint('ordinal >= 0', name='ck_ai_knowledge_chunk_ordinal'),
    sa.ForeignKeyConstraint(['document_id'], ['ai_knowledge_document.document_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('chunk_id'),
    sa.UniqueConstraint('document_id', 'ordinal', name='uq_ai_knowledge_chunk_doc_ordinal')
    )
    op.create_index('ix_ai_knowledge_chunk_document', 'ai_knowledge_chunk', ['document_id', 'ordinal'], unique=False)
    op.create_index('ix_ai_knowledge_chunk_embedding_status', 'ai_knowledge_chunk', ['embedding_status'], unique=False)
    op.create_table('ai_managed_session',
    sa.Column('session_id', sa.Text(), nullable=False),
    sa.Column('platform_id', sa.Text(), nullable=False),
    sa.Column('platform_type', sa.Text(), nullable=False),
    sa.Column('message_type', sa.Text(), nullable=False),
    sa.Column('subject_id', sa.Text(), nullable=False),
    sa.Column('source_labels_json', sa.Text(), nullable=False),
    sa.Column('diagnostic_raw_ids_json', sa.Text(), nullable=False),
    sa.Column('ai_enabled', sa.Integer(), nullable=False),
    sa.Column('persona_id', sa.Text(), nullable=True),
    sa.Column('context_reset_at', sa.Integer(), nullable=True),
    sa.Column('context_reset_by', sa.Text(), nullable=True),
    sa.Column('last_observed_at', sa.Integer(), nullable=True),
    sa.Column('last_user_message_at', sa.Integer(), nullable=True),
    sa.Column('last_ai_message_at', sa.Integer(), nullable=True),
    sa.Column('audit_created_by', sa.Text(), nullable=True),
    sa.Column('audit_updated_by', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.Integer(), nullable=False),
    sa.CheckConstraint("message_type IN ('group', 'private', 'web_chat')", name='ck_ai_managed_session_message_type'),
    sa.CheckConstraint('ai_enabled IN (0, 1)', name='ck_ai_managed_session_ai_enabled'),
    sa.ForeignKeyConstraint(['persona_id'], ['ai_persona.persona_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('session_id'),
    sa.UniqueConstraint('platform_id', 'platform_type', 'message_type', 'subject_id', name='uq_ai_managed_session_identity')
    )
    op.create_index('idx_ai_managed_session_recent', 'ai_managed_session', ['last_observed_at', 'updated_at'], unique=False)
    op.create_index('idx_ai_managed_session_source', 'ai_managed_session', ['platform_id', 'platform_type', 'message_type', 'subject_id'], unique=False)
    op.create_table('ai_model_route_binding',
    sa.Column('binding_id', sa.Text(), nullable=False),
    sa.Column('scope_type', sa.Text(), nullable=False),
    sa.Column('scope_id', sa.Text(), nullable=False),
    sa.Column('task_class', sa.Text(), nullable=False),
    sa.Column('route_id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.Integer(), nullable=False),
    sa.CheckConstraint("scope_type != 'global' OR scope_id = '__global__'", name='ck_ai_model_route_binding_global_sentinel'),
    sa.CheckConstraint("scope_type IN ('global', 'group', 'user', 'conversation')", name='ck_ai_model_route_binding_scope_type'),
    sa.CheckConstraint("task_class IN ('planner_light', 'reply_default', 'reply_roleplay', 'reasoning_heavy', 'memory_extraction', 'tool_orchestration')", name='ck_ai_model_route_binding_task_class'),
    sa.CheckConstraint('length(scope_id) > 0', name='ck_ai_model_route_binding_scope_id_len'),
    sa.ForeignKeyConstraint(['route_id'], ['ai_model_route.route_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('binding_id'),
    sa.UniqueConstraint('scope_type', 'scope_id', 'task_class')
    )
    op.create_index('idx_ai_model_route_binding_route', 'ai_model_route_binding', ['route_id'], unique=False)
    op.create_table('ai_persona_binding',
    sa.Column('binding_id', sa.Text(), nullable=False),
    sa.Column('scope_type', sa.Text(), nullable=False),
    sa.Column('scope_id', sa.Text(), nullable=False),
    sa.Column('persona_id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.Integer(), nullable=False),
    sa.CheckConstraint("scope_type != 'global' OR scope_id = '__global__'", name='ck_ai_persona_binding_global_sentinel'),
    sa.CheckConstraint("scope_type IN ('global', 'group', 'user', 'conversation')", name='ck_ai_persona_binding_scope_type'),
    sa.CheckConstraint('length(scope_id) > 0', name='ck_ai_persona_binding_scope_id_len'),
    sa.ForeignKeyConstraint(['persona_id'], ['ai_persona.persona_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('binding_id'),
    sa.UniqueConstraint('scope_type', 'scope_id')
    )
    op.create_table('ai_relationship_event',
    sa.Column('event_id', sa.Text(), nullable=False),
    sa.Column('affinity_id', sa.Text(), nullable=False),
    sa.Column('platform', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('scene_id', sa.Text(), nullable=True),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('score_delta', sa.Integer(), nullable=False),
    sa.Column('score_after', sa.Integer(), nullable=False),
    sa.Column('mood_tag', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.CheckConstraint("event_type IN ('message', 'manual', 'decay')", name='ck_ai_relationship_event_event_type'),
    sa.CheckConstraint('score_after BETWEEN -100 AND 100', name='ck_ai_relationship_event_score_after'),
    sa.ForeignKeyConstraint(['affinity_id'], ['ai_affinity.affinity_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index('ix_ai_relationship_event_affinity', 'ai_relationship_event', ['affinity_id'], unique=False)
    op.create_index('ix_ai_relationship_event_created_at', 'ai_relationship_event', ['created_at'], unique=False)
    op.create_table('ai_rerank_model',
    sa.Column('model_id', sa.Text(), nullable=False),
    sa.Column('source_id', sa.Text(), nullable=False),
    sa.Column('model_identifier', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Integer(), nullable=False),
    sa.Column('is_default', sa.Integer(), nullable=False),
    sa.Column('extra_params_json', sa.Text(), nullable=False),
    sa.Column('capability_metadata_json', sa.Text(), nullable=False),
    sa.Column('default_options_json', sa.Text(), nullable=False),
    sa.Column('capability_provenance_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.Integer(), nullable=False),
    sa.CheckConstraint('enabled IN (0, 1)', name='ck_ai_rerank_model_enabled'),
    sa.CheckConstraint('is_default IN (0, 1)', name='ck_ai_rerank_model_is_default'),
    sa.CheckConstraint('json_valid(capability_metadata_json)', name='ck_ai_rerank_model_capability_metadata_json'),
    sa.CheckConstraint('json_valid(capability_provenance_json)', name='ck_ai_rerank_model_capability_provenance_json'),
    sa.CheckConstraint('json_valid(default_options_json)', name='ck_ai_rerank_model_default_options_json'),
    sa.CheckConstraint('json_valid(extra_params_json)', name='ck_ai_rerank_model_extra_params_json'),
    sa.ForeignKeyConstraint(['source_id'], ['ai_source.source_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('model_id'),
    sa.UniqueConstraint('source_id', 'model_identifier')
    )
    op.create_index('idx_ai_rerank_model_one_default_per_source', 'ai_rerank_model', ['source_id'], unique=True, sqlite_where=sa.text('is_default = 1'))
    op.create_index('idx_ai_rerank_model_source_id', 'ai_rerank_model', ['source_id'], unique=False)
    op.create_table('ai_stt_model',
    sa.Column('model_id', sa.Text(), nullable=False),
    sa.Column('source_id', sa.Text(), nullable=False),
    sa.Column('model_identifier', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Integer(), nullable=False),
    sa.Column('is_default', sa.Integer(), nullable=False),
    sa.Column('extra_params_json', sa.Text(), nullable=False),
    sa.Column('capability_metadata_json', sa.Text(), nullable=False),
    sa.Column('default_options_json', sa.Text(), nullable=False),
    sa.Column('capability_provenance_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.Integer(), nullable=False),
    sa.CheckConstraint('enabled IN (0, 1)', name='ck_ai_stt_model_enabled'),
    sa.CheckConstraint('is_default IN (0, 1)', name='ck_ai_stt_model_is_default'),
    sa.CheckConstraint('json_valid(capability_metadata_json)', name='ck_ai_stt_model_capability_metadata_json'),
    sa.CheckConstraint('json_valid(capability_provenance_json)', name='ck_ai_stt_model_capability_provenance_json'),
    sa.CheckConstraint('json_valid(default_options_json)', name='ck_ai_stt_model_default_options_json'),
    sa.CheckConstraint('json_valid(extra_params_json)', name='ck_ai_stt_model_extra_params_json'),
    sa.ForeignKeyConstraint(['source_id'], ['ai_source.source_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('model_id'),
    sa.UniqueConstraint('source_id', 'model_identifier')
    )
    op.create_index('idx_ai_stt_model_one_default_per_source', 'ai_stt_model', ['source_id'], unique=True, sqlite_where=sa.text('is_default = 1'))
    op.create_index('idx_ai_stt_model_source_id', 'ai_stt_model', ['source_id'], unique=False)
    op.create_table('ai_tts_model',
    sa.Column('model_id', sa.Text(), nullable=False),
    sa.Column('source_id', sa.Text(), nullable=False),
    sa.Column('model_identifier', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Integer(), nullable=False),
    sa.Column('is_default', sa.Integer(), nullable=False),
    sa.Column('extra_params_json', sa.Text(), nullable=False),
    sa.Column('capability_metadata_json', sa.Text(), nullable=False),
    sa.Column('default_options_json', sa.Text(), nullable=False),
    sa.Column('capability_provenance_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.Integer(), nullable=False),
    sa.CheckConstraint('enabled IN (0, 1)', name='ck_ai_tts_model_enabled'),
    sa.CheckConstraint('is_default IN (0, 1)', name='ck_ai_tts_model_is_default'),
    sa.CheckConstraint('json_valid(capability_metadata_json)', name='ck_ai_tts_model_capability_metadata_json'),
    sa.CheckConstraint('json_valid(capability_provenance_json)', name='ck_ai_tts_model_capability_provenance_json'),
    sa.CheckConstraint('json_valid(default_options_json)', name='ck_ai_tts_model_default_options_json'),
    sa.CheckConstraint('json_valid(extra_params_json)', name='ck_ai_tts_model_extra_params_json'),
    sa.ForeignKeyConstraint(['source_id'], ['ai_source.source_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('model_id'),
    sa.UniqueConstraint('source_id', 'model_identifier')
    )
    op.create_index('idx_ai_tts_model_one_default_per_source', 'ai_tts_model', ['source_id'], unique=True, sqlite_where=sa.text('is_default = 1'))
    op.create_index('idx_ai_tts_model_source_id', 'ai_tts_model', ['source_id'], unique=False)
    op.create_table('chat_message',
    sa.Column('message_id', sa.Text(), nullable=False),
    sa.Column('session_id', sa.Text(), nullable=False),
    sa.Column('platform_message_id', sa.Text(), nullable=True),
    sa.Column('reply_to_message_id', sa.Text(), nullable=True),
    sa.Column('platform_reply_id', sa.Text(), nullable=True),
    sa.Column('author_role', sa.Text(), nullable=False),
    sa.Column('author_id', sa.Text(), nullable=False),
    sa.Column('author_name', sa.Text(), nullable=True),
    sa.Column('message_kind', sa.Text(), nullable=False),
    sa.Column('turn_disposition', sa.Text(), nullable=False),
    sa.Column('directed_to_bot', sa.Integer(), nullable=False),
    sa.Column('mentions_bot', sa.Integer(), nullable=False),
    sa.Column('has_media', sa.Integer(), nullable=False),
    sa.Column('text_content', sa.Text(), nullable=False),
    sa.Column('content_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.CheckConstraint("author_role IN ('user', 'assistant', 'system', 'tool')", name='ck_chat_message_author_role'),
    sa.CheckConstraint("message_kind IN ('text', 'mixed', 'media', 'system', 'tool')", name='ck_chat_message_message_kind'),
    sa.CheckConstraint("turn_disposition IN ('active', 'pruned', 'summarized', 'archived')", name='ck_chat_message_turn_disposition'),
    sa.CheckConstraint('directed_to_bot IN (0, 1)', name='ck_chat_message_directed_to_bot'),
    sa.CheckConstraint('has_media IN (0, 1)', name='ck_chat_message_has_media'),
    sa.CheckConstraint('mentions_bot IN (0, 1)', name='ck_chat_message_mentions_bot'),
    sa.ForeignKeyConstraint(['session_id'], ['chat_session.session_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_index('idx_chat_message_created_at', 'chat_message', ['created_at'], unique=False)
    op.create_index('idx_chat_message_platform_message_id', 'chat_message', ['platform_message_id'], unique=False)
    op.create_index('idx_chat_message_session_created', 'chat_message', ['session_id', 'created_at'], unique=False)
    op.create_table('chat_session_context_summary',
    sa.Column('session_id', sa.Text(), nullable=False),
    sa.Column('summary_text', sa.Text(), nullable=False),
    sa.Column('source_until_message_id', sa.Text(), nullable=False),
    sa.Column('source_until_created_at', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.Integer(), nullable=False),
    sa.CheckConstraint('length(summary_text) > 0', name='ck_context_summary_nonempty'),
    sa.ForeignKeyConstraint(['session_id'], ['chat_session.session_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_table('group_disabled_plugin',
    sa.Column('group_id', sa.Text(), nullable=False),
    sa.Column('plugin_id', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['group_state.group_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('group_id', 'plugin_id')
    )
    op.create_table('ai_delivery_attempt',
    sa.Column('attempt_id', sa.Text(), nullable=False),
    sa.Column('task_id', sa.Text(), nullable=False),
    sa.Column('trace_id', sa.Text(), nullable=False),
    sa.Column('session_id', sa.Text(), nullable=False),
    sa.Column('delivery_intent', sa.Text(), nullable=False),
    sa.Column('platform', sa.Text(), nullable=False),
    sa.Column('scene_type', sa.Text(), nullable=False),
    sa.Column('scene_id', sa.Text(), nullable=False),
    sa.Column('message_preview', sa.Text(), nullable=False),
    sa.Column('message_hash', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('diagnostics_json', sa.Text(), nullable=False),
    sa.Column('channel', sa.Text(), nullable=True),
    sa.Column('remote_message_id', sa.Text(), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('delivered_at', sa.Integer(), nullable=True),
    sa.Column('failed_at', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.Integer(), nullable=False),
    sa.CheckConstraint("scene_type IN ('group', 'private')", name='ck_ai_delivery_attempt_scene_type'),
    sa.CheckConstraint("status IN ('pending', 'delivered', 'failed')", name='ck_ai_delivery_attempt_status'),
    sa.CheckConstraint('attempt_count >= 0', name='ck_ai_delivery_attempt_attempt_count'),
    sa.ForeignKeyConstraint(['task_id'], ['ai_future_task.task_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('attempt_id')
    )
    op.create_index('ix_ai_delivery_attempt_delivered', 'ai_delivery_attempt', ['task_id', 'delivery_intent'], unique=True, sqlite_where=sa.text("status = 'delivered'"))
    op.create_index('ix_ai_delivery_attempt_pending', 'ai_delivery_attempt', ['task_id', 'delivery_intent'], unique=True, sqlite_where=sa.text("status = 'pending'"))
    op.create_index('ix_ai_delivery_attempt_task_intent', 'ai_delivery_attempt', ['task_id', 'delivery_intent', 'status'], unique=False)
    op.create_index('ix_ai_delivery_attempt_updated_at', 'ai_delivery_attempt', ['updated_at'], unique=False)
    op.create_table('ai_memory_item',
    sa.Column('memory_id', sa.Text(), nullable=False),
    sa.Column('anchor_type', sa.Text(), nullable=False),
    sa.Column('anchor_id', sa.Text(), nullable=False),
    sa.Column('memory_layer', sa.Text(), nullable=False),
    sa.Column('memory_kind', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_editable', sa.Integer(), nullable=False),
    sa.Column('lifecycle_state', sa.Text(), nullable=False),
    sa.Column('default_use_mode', sa.Text(), nullable=False),
    sa.Column('governance_reason', sa.Text(), nullable=True),
    sa.Column('source_message_id', sa.Text(), nullable=True),
    sa.Column('salience', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('last_recalled_at', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.CheckConstraint("anchor_type IN ('operator', 'scene', 'participant', 'user', 'project')", name='ck_ai_memory_item_anchor_type'),
    sa.CheckConstraint("default_use_mode IN ('ignore', 'silent', 'context', 'explicit')", name='ck_ai_memory_item_default_use_mode'),
    sa.CheckConstraint("lifecycle_state IN ('candidate', 'active', 'suppressed', 'archived')", name='ck_ai_memory_item_lifecycle_state'),
    sa.CheckConstraint("memory_kind IN ('fact', 'preference', 'relationship', 'note', 'impression')", name='ck_ai_memory_item_memory_kind'),
    sa.CheckConstraint("memory_layer IN ('summary', 'long_term', 'knowledge', 'operator')", name='ck_ai_memory_item_memory_layer'),
    sa.CheckConstraint('confidence BETWEEN 0.0 AND 1.0', name='ck_ai_memory_item_confidence'),
    sa.CheckConstraint('is_editable IN (0, 1)', name='ck_ai_memory_item_is_editable'),
    sa.CheckConstraint('salience BETWEEN 0.0 AND 1.0', name='ck_ai_memory_item_salience'),
    sa.ForeignKeyConstraint(['source_message_id'], ['chat_message.message_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('memory_id'),
    sa.UniqueConstraint('anchor_type', 'anchor_id', 'memory_layer', 'memory_kind', 'content', name='uq_ai_memory_item_anchor_content')
    )
    op.create_index('ix_ai_memory_item_anchor_layer_kind', 'ai_memory_item', ['anchor_type', 'anchor_id', 'memory_layer', 'memory_kind'], unique=False)
    op.create_index('ix_ai_memory_item_lifecycle_created', 'ai_memory_item', ['lifecycle_state', 'created_at'], unique=False)
    op.create_table('ai_model_profile',
    sa.Column('profile_id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('model_id', sa.Text(), nullable=False),
    sa.Column('task_class', sa.Text(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Integer(), nullable=False),
    sa.Column('fallback_profile_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.Integer(), nullable=False),
    sa.CheckConstraint("task_class IN ('planner_light', 'reply_default', 'reply_roleplay', 'reasoning_heavy', 'memory_extraction', 'tool_orchestration')", name='ck_ai_model_profile_task_class'),
    sa.CheckConstraint('enabled IN (0, 1)', name='ck_ai_model_profile_enabled'),
    sa.ForeignKeyConstraint(['fallback_profile_id'], ['ai_model_profile.profile_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['model_id'], ['ai_chat_model.model_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('profile_id')
    )
    op.create_table('ai_model_binding',
    sa.Column('binding_id', sa.Text(), nullable=False),
    sa.Column('scope_type', sa.Text(), nullable=False),
    sa.Column('scope_id', sa.Text(), nullable=False),
    sa.Column('profile_id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.Integer(), nullable=False),
    sa.CheckConstraint("scope_type != 'global' OR scope_id = '__global__'", name='ck_ai_model_binding_global_sentinel'),
    sa.CheckConstraint("scope_type IN ('global', 'group', 'user', 'conversation')", name='ck_ai_model_binding_scope_type'),
    sa.CheckConstraint('length(scope_id) > 0', name='ck_ai_model_binding_scope_id_len'),
    sa.ForeignKeyConstraint(['profile_id'], ['ai_model_profile.profile_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('binding_id'),
    sa.UniqueConstraint('scope_type', 'scope_id')
    )
    op.create_table('ai_model_route_member',
    sa.Column('route_member_id', sa.Text(), nullable=False),
    sa.Column('route_id', sa.Text(), nullable=False),
    sa.Column('profile_id', sa.Text(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.Integer(), nullable=False),
    sa.CheckConstraint('enabled IN (0, 1)', name='ck_ai_model_route_member_enabled'),
    sa.CheckConstraint('position >= 0', name='ck_ai_model_route_member_position'),
    sa.CheckConstraint('weight > 0', name='ck_ai_model_route_member_weight'),
    sa.ForeignKeyConstraint(['profile_id'], ['ai_model_profile.profile_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['route_id'], ['ai_model_route.route_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('route_member_id'),
    sa.UniqueConstraint('route_id', 'position'),
    sa.UniqueConstraint('route_id', 'profile_id')
    )
    op.create_index('idx_ai_model_route_member_route', 'ai_model_route_member', ['route_id', 'enabled', 'position'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_ai_model_route_member_route', table_name='ai_model_route_member')
    op.drop_table('ai_model_route_member')
    op.drop_table('ai_model_binding')
    op.drop_table('ai_model_profile')
    op.drop_index('ix_ai_memory_item_lifecycle_created', table_name='ai_memory_item')
    op.drop_index('ix_ai_memory_item_anchor_layer_kind', table_name='ai_memory_item')
    op.drop_table('ai_memory_item')
    op.drop_index('ix_ai_delivery_attempt_updated_at', table_name='ai_delivery_attempt')
    op.drop_index('ix_ai_delivery_attempt_task_intent', table_name='ai_delivery_attempt')
    op.drop_index('ix_ai_delivery_attempt_pending', table_name='ai_delivery_attempt', sqlite_where=sa.text("status = 'pending'"))
    op.drop_index('ix_ai_delivery_attempt_delivered', table_name='ai_delivery_attempt', sqlite_where=sa.text("status = 'delivered'"))
    op.drop_table('ai_delivery_attempt')
    op.drop_table('group_disabled_plugin')
    op.drop_table('chat_session_context_summary')
    op.drop_index('idx_chat_message_session_created', table_name='chat_message')
    op.drop_index('idx_chat_message_platform_message_id', table_name='chat_message')
    op.drop_index('idx_chat_message_created_at', table_name='chat_message')
    op.drop_table('chat_message')
    op.drop_index('idx_ai_tts_model_source_id', table_name='ai_tts_model')
    op.drop_index('idx_ai_tts_model_one_default_per_source', table_name='ai_tts_model', sqlite_where=sa.text('is_default = 1'))
    op.drop_table('ai_tts_model')
    op.drop_index('idx_ai_stt_model_source_id', table_name='ai_stt_model')
    op.drop_index('idx_ai_stt_model_one_default_per_source', table_name='ai_stt_model', sqlite_where=sa.text('is_default = 1'))
    op.drop_table('ai_stt_model')
    op.drop_index('idx_ai_rerank_model_source_id', table_name='ai_rerank_model')
    op.drop_index('idx_ai_rerank_model_one_default_per_source', table_name='ai_rerank_model', sqlite_where=sa.text('is_default = 1'))
    op.drop_table('ai_rerank_model')
    op.drop_index('ix_ai_relationship_event_created_at', table_name='ai_relationship_event')
    op.drop_index('ix_ai_relationship_event_affinity', table_name='ai_relationship_event')
    op.drop_table('ai_relationship_event')
    op.drop_table('ai_persona_binding')
    op.drop_index('idx_ai_model_route_binding_route', table_name='ai_model_route_binding')
    op.drop_table('ai_model_route_binding')
    op.drop_index('idx_ai_managed_session_source', table_name='ai_managed_session')
    op.drop_index('idx_ai_managed_session_recent', table_name='ai_managed_session')
    op.drop_table('ai_managed_session')
    op.drop_index('ix_ai_knowledge_chunk_embedding_status', table_name='ai_knowledge_chunk')
    op.drop_index('ix_ai_knowledge_chunk_document', table_name='ai_knowledge_chunk')
    op.drop_table('ai_knowledge_chunk')
    op.drop_index('ix_ai_future_task_updated_at', table_name='ai_future_task')
    op.drop_index('ix_ai_future_task_status_trigger', table_name='ai_future_task')
    op.drop_index('ix_ai_future_task_session', table_name='ai_future_task')
    op.drop_table('ai_future_task')
    op.drop_index('idx_ai_embedding_model_source_id', table_name='ai_embedding_model')
    op.drop_index('idx_ai_embedding_model_one_default_per_source', table_name='ai_embedding_model', sqlite_where=sa.text('is_default = 1'))
    op.drop_table('ai_embedding_model')
    op.drop_index('idx_ai_chat_model_source_id', table_name='ai_chat_model')
    op.drop_index('idx_ai_chat_model_one_default_per_source', table_name='ai_chat_model', sqlite_where=sa.text('is_default = 1'))
    op.drop_table('ai_chat_model')
    op.drop_table('webui_auth_secret')
    op.drop_index('idx_webui_account_username', table_name='webui_account')
    op.drop_table('webui_account')
    op.drop_table('plugin_state')
    op.drop_table('group_state')
    op.drop_index('idx_chat_session_last_message_at', table_name='chat_session')
    op.drop_table('chat_session')
    op.drop_table('apeiria_schema_meta')
    op.drop_table('ai_tool_policy')
    op.drop_table('ai_source')
    op.drop_table('ai_runtime_settings')
    op.drop_index('ix_ai_profile_last_interaction', table_name='ai_profile')
    op.drop_table('ai_profile')
    op.drop_table('ai_persona')
    op.drop_table('ai_model_usage_hourly')
    op.drop_index('ix_ai_model_usage_event_trace', table_name='ai_model_usage_event')
    op.drop_index('ix_ai_model_usage_event_session', table_name='ai_model_usage_event')
    op.drop_index('ix_ai_model_usage_event_created_at', table_name='ai_model_usage_event')
    op.drop_table('ai_model_usage_event')
    op.drop_index('idx_ai_model_route_task_class', table_name='ai_model_route')
    op.drop_table('ai_model_route')
    op.drop_index('ix_ai_knowledge_document_updated_at', table_name='ai_knowledge_document')
    op.drop_table('ai_knowledge_document')
    op.drop_index('ix_ai_affinity_user', table_name='ai_affinity')
    op.drop_table('ai_affinity')
    op.drop_table('access_rule')
    # ### end Alembic commands ###
