"""Public AI session runtime contracts."""

from __future__ import annotations

from .context import (
    DeliveryTarget,
    MergeMetadata,
    RuntimeMode,
    RuntimeTurnSource,
    TurnContext,
)
from .context_adapter import build_turn_context
from .engine import (
    AISessionTurnEngine,
    DefaultRuntimeCommitStage,
    DefaultRuntimeContextStage,
    DefaultRuntimeExecutionStage,
    DefaultRuntimeObservationStage,
    DefaultRuntimePlanningStage,
    DefaultRuntimePolicyStage,
    DefaultRuntimeTraceStage,
)
from .hard_rules import (
    decide_runtime_hard_rule,
    map_legacy_skip_to_runtime_decision,
)
from .planning import (
    RuntimePromptPlanningInput,
    build_initial_runtime_reply_prompt_diagnostics,
    build_initial_runtime_reply_prompt_messages,
    build_initial_runtime_reply_prompt_packet,
    plan_runtime_turn,
)
from .runner import AgentRunner, RuntimeAgentRunner
from .runtime import (
    AISessionRuntime,
    DeferState,
    InMemoryAISessionRuntime,
    InMemoryAISessionRuntimeResolver,
    PendingAmbientMessage,
    SessionRuntimePolicy,
    WaitState,
)
from .stages import (
    RuntimeCommitResult,
    RuntimeCommitStage,
    RuntimeContextBundle,
    RuntimeContextStage,
    RuntimeExecutionOutcome,
    RuntimeExecutionStage,
    RuntimeObservationStage,
    RuntimePlanningInput,
    RuntimePlanningStage,
    RuntimePolicyOutcome,
    RuntimePolicyStage,
    RuntimeStageName,
    RuntimeTraceOutcome,
    RuntimeTraceStage,
    RuntimeTurnPlan,
)
from .strategy import (
    MAX_HARD_RULE_EVIDENCE_ITEMS,
    RuntimeHardRuleAction,
    RuntimeHardRuleDecision,
    RuntimeHardRuleReasonCode,
)
from .tools import (
    DEFAULT_TOOL_AWARENESS_CATEGORIES,
    ToolExposurePlan,
    ToolOrchestrator,
    apply_tool_exposure_allowlist,
    build_default_tool_exposure_plan,
    compile_tool_exposure_provider_schema,
)
from .trace import TurnTrace, project_turn_trace

__all__ = [
    "DEFAULT_TOOL_AWARENESS_CATEGORIES",
    "MAX_HARD_RULE_EVIDENCE_ITEMS",
    "AISessionRuntime",
    "AISessionTurnEngine",
    "AgentRunner",
    "DefaultRuntimeCommitStage",
    "DefaultRuntimeContextStage",
    "DefaultRuntimeExecutionStage",
    "DefaultRuntimeObservationStage",
    "DefaultRuntimePlanningStage",
    "DefaultRuntimePolicyStage",
    "DefaultRuntimeTraceStage",
    "DeferState",
    "DeliveryTarget",
    "InMemoryAISessionRuntime",
    "InMemoryAISessionRuntimeResolver",
    "MergeMetadata",
    "PendingAmbientMessage",
    "RuntimeAgentRunner",
    "RuntimeCommitResult",
    "RuntimeCommitStage",
    "RuntimeContextBundle",
    "RuntimeContextStage",
    "RuntimeExecutionOutcome",
    "RuntimeExecutionStage",
    "RuntimeHardRuleAction",
    "RuntimeHardRuleDecision",
    "RuntimeHardRuleReasonCode",
    "RuntimeMode",
    "RuntimeObservationStage",
    "RuntimePlanningInput",
    "RuntimePlanningStage",
    "RuntimePolicyOutcome",
    "RuntimePolicyStage",
    "RuntimePromptPlanningInput",
    "RuntimeStageName",
    "RuntimeTraceOutcome",
    "RuntimeTraceStage",
    "RuntimeTurnPlan",
    "RuntimeTurnSource",
    "SessionRuntimePolicy",
    "ToolExposurePlan",
    "ToolOrchestrator",
    "TurnContext",
    "TurnTrace",
    "WaitState",
    "apply_tool_exposure_allowlist",
    "build_default_tool_exposure_plan",
    "build_initial_runtime_reply_prompt_diagnostics",
    "build_initial_runtime_reply_prompt_messages",
    "build_initial_runtime_reply_prompt_packet",
    "build_turn_context",
    "compile_tool_exposure_provider_schema",
    "decide_runtime_hard_rule",
    "map_legacy_skip_to_runtime_decision",
    "plan_runtime_turn",
    "project_turn_trace",
]
